spring:
  profiles:
    active: @spring.profiles.active@
    include: mybatisplus
  application:
    name: demo
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://192.168.52.129:3306/mp_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
  #    username: xsw
  #    password: 827303Ok.
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://mysql.xsw:3306/mp_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: xsw
          password: 827303Ok.
  #集群配置
  redis:
    cluster:
      nodes: 192.168.52.129:6379,192.168.52.129:6380,192.168.52.129:6381,192.168.52.130:6379,192.168.52.130:6380,192.168.52.130:6381 #集群节点
    lettuce:
      pool:
        max-active: 10  #连接池最大连接数
        max-idle: 8     #连接池中最大空闲连接数
        max-wait: -1ms  #连接池最大等待阻塞时间
        min-idle: 0     #连接池中最小空闲数
      timeout: 5000      #访问超时时间

# 单机配置
#  redis:
#    host: localhost
#    port: 6379
#    timeout: 1000
#    jedis:
#      pool:
#        min-idle: 5
#        max-idle: 10
#        max-wait: -1

  #微服务相关
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址
    sentinel:
      transport:
        dashboard: localhost:8080 # sentinel控制台地址
      web-context-unify: false # 关闭context整合
      datasource:
        flow:
          nacos:
            server-addr: localhost:8848 # nacos地址
            dataId: orderservice-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow # 还可以是：degrade、authority、param-flow
#      discovery:
#        namespace: 4d6ce343-9e1b-44df-a90f-2cf2b6b3d177 # dev环境
#        ephemeral: false # 是否是临时实例
  #MQ配置
  rabbitmq:
    host: mq.xsw
    port: 5672
    username: admin
    password: 123
    publisher-confirm-type: correlated
    publisher-returns: true
    virtual-host: /

  #es配置
  elasticsearch:
    rest:
      uris:
        - http://es.xtravel:9200

#rpc,feign
#userservice:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - userservice
  #请求超时时间(不一定要配)
  ReadTimeout: 600000 #处理超时时间 默认5秒
  ConnectTimeout: 600000 #连接超时时间 默认2秒
feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
  sentinel:
    enabled: true # 开启feign对sentinel的支持

server:
  port: 9977
  servlet:
    context-path: /${spring.application.name}
